version: '3.9'
services:
  web:
    build: .
    command:  gunicorn dates_fact.wsgi:application --bind 0.0.0.0:8000
#    command: python3 manage.py runserver
    volumes:
      - .:/app
      - static_volume:/app/static
    expose:
      - 8000
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DEBUG=${DEBUG}

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/static
    ports:
      - 3333:80
    depends_on:
      - web
volumes:
   static_volume:

