# Generated by Django 4.0.4 on 2022-05-15 15:15

import dates.models.dates
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateFact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month_number', models.IntegerField(validators=[dates.models.dates.validate_month])),
                ('day', models.IntegerField(validators=[dates.models.dates.validate_day])),
                ('fact', models.TextField(verbose_name='Interesting Fact About the Date')),
                ('days_checked', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Date Event Fact',
                'unique_together': {('month_number', 'day')},
            },
        ),
    ]
